package pl.quickside.ownshop.BO;

// default package
// Generated 2014-01-21 20:53:49 by Hibernate Tools 3.4.0.CR1

/**
 * OwnShop generated by hbm2java
 */
public class OwnShopBO implements java.io.Serializable, Comparable<OwnShopBO> {

	private Integer id;
	private char wojKod;
	private String miasto;
	private String kodPocztowy;
	private String ulica;
	private String rodzaj;
	private String dodInf;
	private String godzOtw;

	public String getDodInf() {
		return dodInf;
	}

	public void setDodInf(String dodInf) {
		this.dodInf = dodInf;
	}

	public OwnShopBO() {
	}

	public OwnShopBO(char wojKod, String miasto, String kodPocztowy,
			String ulica, String rodzaj) {
		this.wojKod = wojKod;
		this.miasto = miasto;
		this.kodPocztowy = kodPocztowy;
		this.ulica = ulica;
		this.rodzaj = rodzaj;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public char getWojKod() {
		return this.wojKod;
	}

	public void setWojKod(char wojKod) {
		this.wojKod = wojKod;
	}

	public String getMiasto() {
		return this.miasto;
	}

	public void setMiasto(String miasto) {
		this.miasto = miasto;
	}

	public String getKodPocztowy() {
		return this.kodPocztowy;
	}

	public void setKodPocztowy(String kodPocztowy) {
		this.kodPocztowy = kodPocztowy;
	}

	public String getUlica() {
		return this.ulica;
	}

	public void setUlica(String ulica) {
		this.ulica = ulica;
	}

	public String getRodzaj() {
		return this.rodzaj;
	}

	public void setRodzaj(String rodzaj) {
		this.rodzaj = rodzaj;
	}

	public String getGodzOtw() {
		return godzOtw;
	}

	public void setGodzOtw(String godzOtw) {
		this.godzOtw = godzOtw;
	}

	@Override
	public int compareTo(OwnShopBO o) {
		int sort = miasto.compareTo(o.miasto);
		
		if(sort == 0){
			miasto.compareTo(o.miasto);
		}
		return sort;
	}

}
