package pl.quickside.welcomescreen.BO;

// default package
// Generated 2014-01-03 13:25:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Aktual generated by hbm2java
 */
public class AktualBO implements java.io.Serializable {

	private Integer id;
	private String text;
	private byte[] images;
	private String tytul;
	private String czas;

	public AktualBO() {
	}

	public AktualBO(String text) {
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public byte[] getImages() {
		return images;
	}

	public void setImages(byte[] images) {
		this.images = images;
	}

	public String getTytul() {
		return tytul;
	}

	public void setTytul(String tytul) {
		this.tytul = tytul;
	}

	public String getCzas() {
		return czas;
	}

	public void setCzas(String czas) {
		this.czas = czas;
	}

}
