package pl.quickside.welcomescreen.BO;

// Generated 2014-01-13 19:18:23 by Hibernate Tools 3.4.0.CR1

/**
 * Promocje generated by hbm2java
 */
public class PromocjeBO implements java.io.Serializable {

	private Integer id;
	private String text;

	public PromocjeBO() {
	}

	public PromocjeBO(String text) {
		this.text = text;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
