package pl.quickside.collect.BO;
// default package
// Generated 2014-01-30 19:37:27 by Hibernate Tools 3.4.0.CR1

/**
 * Collect generated by hbm2java
 */
public class CollectBO implements java.io.Serializable {

	private Integer id;
	private String idKod;
	private String kodUbrania;
	private String nazwaPrd;
	private byte[] images;
	private byte[] small;
	private byte[] thumb;
	private String opis;
	private String dodOpis;
	private String warSprz;
	private String rozmiar;
	private byte[] praniePhoto;
	private String skladUbrania;
	private String kolor;
	private char prdTyg;

	public CollectBO() {
	}

	public CollectBO(String idKod, String kodUbrania, String nazwaPrd,
			byte[] images, byte[] small, String opis, String dodOpis,
			String warSprz, String rozmiar, byte[] praniePhoto,
			String skladUbrania, String kolor, char prdTyg) {
		this.idKod = idKod;
		this.kodUbrania = kodUbrania;
		this.nazwaPrd = nazwaPrd;
		this.images = images;
		this.small = small;
		this.opis = opis;
		this.dodOpis = dodOpis;
		this.warSprz = warSprz;
		this.rozmiar = rozmiar;
		this.praniePhoto = praniePhoto;
		this.skladUbrania = skladUbrania;
		this.kolor = kolor;
		this.prdTyg = prdTyg;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getIdKod() {
		return this.idKod;
	}

	public void setIdKod(String idKod) {
		this.idKod = idKod;
	}

	public String getKodUbrania() {
		return this.kodUbrania;
	}

	public void setKodUbrania(String kodUbrania) {
		this.kodUbrania = kodUbrania;
	}

	public String getNazwaPrd() {
		return this.nazwaPrd;
	}

	public void setNazwaPrd(String nazwaPrd) {
		this.nazwaPrd = nazwaPrd;
	}

	public byte[] getImages() {
		return this.images;
	}

	public void setImages(byte[] images) {
		this.images = images;
	}

	public byte[] getSmall() {
		return this.small;
	}

	public void setSmall(byte[] small) {
		this.small = small;
	}

	public byte[] getThumb() {
		return thumb;
	}

	public void setThumb(byte[] thumb) {
		this.thumb = thumb;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public String getDodOpis() {
		return this.dodOpis;
	}

	public void setDodOpis(String dodOpis) {
		this.dodOpis = dodOpis;
	}

	public String getWarSprz() {
		return this.warSprz;
	}

	public void setWarSprz(String warSprz) {
		this.warSprz = warSprz;
	}

	public String getRozmiar() {
		return this.rozmiar;
	}

	public void setRozmiar(String rozmiar) {
		this.rozmiar = rozmiar;
	}

	public byte[] getPraniePhoto() {
		return this.praniePhoto;
	}

	public void setPraniePhoto(byte[] praniePhoto) {
		this.praniePhoto = praniePhoto;
	}

	public String getSkladUbrania() {
		return this.skladUbrania;
	}

	public void setSkladUbrania(String skladUbrania) {
		this.skladUbrania = skladUbrania;
	}

	public String getKolor() {
		return this.kolor;
	}

	public void setKolor(String kolor) {
		this.kolor = kolor;
	}

	public char getPrdTyg() {
		return this.prdTyg;
	}

	public void setPrdTyg(char prdTyg) {
		this.prdTyg = prdTyg;
	}

}
